name: Java CI

#on: [push, pull_request]
on:
  push:
  pull_request:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    if: (github.event_name == 'schedule' && github.repository == 'primefaces-extensions/primefaces-integration-tests') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}, Profile ${{ matrix.profile }}
    strategy:
        matrix:
            java: [8, 11]
            profile: ['headless-mode', 'headless-mode,chrome']

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Checkout PrimeFaces
        uses: actions/checkout@master
        with:
          repository: primefaces/primefaces
          path: primefaces
      - name: Build PrimeFaces
        run: cd primefaces && mvn install && cd ..
      - name: Checkout PrimeFaces Selenium
        uses: actions/checkout@master
        with:
          repository: primefaces-extensions/primefaces-selenium
          path: primefaces-selenium
      - name: Build PrimeFaces Selenium
        run: cd primefaces-selenium && mvn install && cd ..
      - name: Build with Maven
        run: mvn -B -V clean install -P${{ matrix.profile }}
